server:
  port: 8090
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/group
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true

  messages:
    basename: messages,errors

  data:
    web:
      pageable:
        default-page-size: 5

logging.level:
#  root: DEBUG
  org.hibernate.SQL: debug
#   org.hibernate.type: trace

file:
  dir: C:/toyProject/group/upload/

